### ISSUE TITLE
დამატებითი ქულა

### ISSUE THREAD

**Issue by LukeSamkharadze** [freeuni-paradigms/assn-2-six-degrees#1]
დავალების PDF ფაილში ნახსენები იყო დამატებითი ქულა, კონკრეტული ოპტიმიზაციის გაკეთების შემთხვევაში, და ეს რომ დავწეროთ მოგვემატება ქულა? 

> Uses a bidirectional search from both actor endpoints, building larger and larger search trees from each of them, and seeing if any of their branches touch.  This is a very effective way of focusing the search so that paths of length 4, 5, and 6 can be more quickly discovered.  Email me if you want some more details on this one.  This last optimization is substantial and can get you some **extra credit** if done nicely.

**Comment by iarigby** [comment]
არა. READMEში რაც წერია მაგის მიხედვით ფასდება, მაგრამ ქულის გარეშეც
სასარგებლოა მაგ ოპტიმიზაციის გაკეთება.
