### ISSUE TITLE
zip.sh

### ISSUE THREAD

**Issue by lgela18** [freeuni-paradigms/assn-2-six-degrees#2]
zip დავაყენე: (sudo apt-get install zip unzip), თუმცა (./zip.sh) ან (sh zip.sh) გაშვებისას ამას მიწერს:
install zip command
/usr/bin/zip

**Comment by iarigby** [comment]
როგორც წერია, zip command უნდა დააინსტალირო

**Comment by lgela18** [comment]
ეგეთი ვერაფერი ვნახე და ზუსტად როგორ უნდა დავაყენო?

**Comment by iarigby** [comment]
sudo apt-get install zip
https://www.google.com/search?client=firefox-b-d&q=ubuntu+install+zip

sudo pacman -S zip
https://www.google.com/search?client=firefox-b-d&q=arch+install+zip

ან ამ ორის მსგავსად დაგუგლე შენი დისტრიბუციისთვის.

**Comment by lgela18** [comment]
უბუნტუ მაქ, პირველი გავაკეთე მაგრამ არუშველა მაგან

**Comment by iarigby** [comment]
ოქეი ხვალ ლეპტოპთან რომ ვიქნები გავარკვიოთ.

**Comment by iarigby** [comment]
გუშინ ძალიან დაღლილზე წავიკითხე და დასაწყისშივე გეწერა რომ დააყენე უკვე, ბოდიში რომ გამომრჩა და არასწორად მიგითითე თავიდან. შეგიძლია zip.sh სკრიპტი გახსნა რომელიმე ედიტორში და პირველი ექვსი ხაზი (`fi`-ს ჩათვლით) წაშალო? და თავიდან სცადე გაშვება

**Comment by lgela18** [comment]
./zip.sh: 10: [[: not found
./zip.sh: 14: [[: not found
	zip warning: missing end signature--probably not a zip file (did you
	zip warning: remember to use binary mode when you transferred it?)
	zip warning: (if you are trying to read a damaged archive try -F)

zip error: Zip file structure invalid (imdb.cc)

ეხლა ამას მწერს  config_files ზე.
 ~/.config/paradigms ფაილი კიდე ვერ ვიპოვე და მაგის ბრალი ხოარაა?

**Comment by lgela18** [comment]
1    
2    # if ! command -v zip &> /dev/null
3    # then
4    # 	echo "install zip command"
5    # 	exit
6    # fi
7    
8    config_file=~/.config/paradigms
9    
10    if [[ -f "$config_file" ]]; then
11	source $config_file
12    fi
13    
14    if [[ -z "$emailid" ]]; then
15   	read -p "enter id: " emailid
16	echo "emailid=$emailid" > $config_file
17    fi
18    
19    zip $emailid imdb.cc six-degrees.cc
20

აი 10 და 14 ხაზებზე რო წერდა ერორს ესენია მანდ

**Comment by iarigby** [comment]
[[ და ]] ერთი [ და ] -ებით ჩაანაცვლე მაგ ხაზებზე.

და

პირველ ხაზზე მიუწერე ეს `#!/bin/sh`

**Comment by lgela18** [comment]
ეხლა ეგ პაილი გააკეთა შიგნით ცჰემი სახელიც მიაწერა მაგრამ ყოველ ჯერზე მთხოვს სახელს და ამას მიწერს: 
./zip.sh: 11: source: not found

**Comment by iarigby** [comment]
პირველ ხაზზე `#!/bin/sh`-ს მაგივრად დაწერე `#!/bin/bash` და წესით უნდა იმუშაოს ერორის გარეშე.

თუ არა და ყოველ ჯერზე შეიყვანე ხოლმე მაშინ id

P.S მადლობა რომ არ დანებდი და დაწერე ერორები, ჩავასწორებ მომავალ დავალებებში რომ ყველასთან კარგად იმუშაოს <3

**Comment by lgela18** [comment]
ერორს არღარ აგდებს მაგრამ არც zip ავს, და არც სახელს მეკითხება(~/.config/paradigms ეს ფაილიც არსებობს).

ისე ამას რო ვწერ მუშაობს zip saxeli imdb.cc six-degrees.cc.

zsh რო ვიყენებ bash ის მაგივრად მაგის პრობლემა ხოარაა? 
(#!/bin/zsh  ესეც ვცადე მაგრამ იგივეს აკეთებს).

**Comment by iarigby** [comment]
არა, მეც მაგას ვიყენებ.

ალბათ ერორზე არასწორად შეინახა და წაშალე ~/.config/paradigms.

**Comment by lgela18** [comment]
გავაკეთე მაგრამ პირველზე მთოვს სახელს იქ სწორად წერს (emailid=saxeli) და მერე არ ზიპავს
