### ISSUE TITLE
imdb test issue

### ISSUE THREAD

**Issue by kpaik18** [freeuni-paradigms/assn-2-six-degrees#3]
imdb.cc-ს ტესტირებას ვერ ვახერხებ, და imdb-test-linux რო ეგ როგორ უნდა გავუშვა?

**Comment by iarigby** [comment]
@freeuni-paradigms/section-leaders

**Comment by bes01** [comment]
./imdb-test-linux ოღონდ executable უნდა გახადო, ფროფერთიებში შედი მაგ ფაილის და მოუნიშნე ეგ ველი.

**Comment by LevanSamadashvili** [comment]
executable მაქვს და რომ ვუშვებ segmentation fault მიგდებს, მოვუხერხებრამეს? :Dდ

**Comment by tsakh** [comment]
მეც executable მაქვს და მაინც Segmentation fault (core dumped)-ს წერს და როგორ უნდა გამოვასწორო?

**Comment by Gvantsats** [comment]
მაგ შეცდომას აგდებს როცა ისეთ მეხსიერებას მიმართავ რომელიც შენ არ გეკუთვნის. კოდს გადახედეთ სადმე არასწორად ხომ არ მიმართავთ მეხსიერებას.

**Comment by tsakh** [comment]
ჯერ არ ჩამიწერია არაფერი :დ მაინტერესებდა როგორ მუშაობდა

**Comment by d-chechelashvili** [comment]
./imdb-test-linux ს აქვს პრობლემა მემგონი, ./imdb-test გაუშვით უბრალოდ და ჩვეულებრივად უნდა იმუშაოს თუ სწორად მახსოვს

**Comment by d-chechelashvili** [comment]
უფს, ახლა გადავამოწმე, ტესტერი მეგონა ეგ და თურმე sample აპლიკაცია ყოფილა. ვერ გავუშვი ვერც მე :დდდ

**Comment by d-chechelashvili** [comment]
მოკლედ მაგის გაშვება ითხოვს რომ სპეციფიკური path-ის ფოლდერში გქონდეთ data და შემდეგ უნდა გაუშვათ **OSTYPE=linux ./imdb-test-linux** ბრძანება.  data-ს ლოკაცია უნდა იყოს /usr/class/cs107/assignments/

დეტალური ინსტურქცია იქნება ასე:
cd /usr
sudo mkdir class
sudo chown თქვენი იუზერის სახელი class
cd class
mkdir cs107
cd cs107
mkdir assignments
cd assignments
          .
 დადექით(ტერმინალით) თქვენი დავალების ფოლდერში(სადაც დატა ფოლდერიცაა და სემფლიც)
          .
cp data /usr/class/cs107/assignments/assn-2-six-degrees-data -r (ეს ბრძანება აკოპირებს დატა ფოლდერს მისთვის სფეციფიკურად შექმნილ ფოლდერში)

გაუშვით OSTYPE=linux ./imdb-test-linux
