### ISSUE TITLE
ტესტებიიიიი

### ISSUE THREAD

**Issue by LukeSamkharadze** [freeuni-paradigms/assn-2-six-degrees#4]
ამ საშინელი ტესტების გადამკიდე რაღაც გაუგებრობას წავაწყდი და იქნებ დამეხმაროთ.

როდესაც საბოლოო ბილიკს ანუ path-ს ვიპოვი ორ მსახიობს შორის, შემდგომ ჩვეულებრივად გამომაქვს `cout << path`-ის მეშვეობით, მაგრამ არცერთ ტესტზე არ გადის. 

ტესტებზე რა მსახიობებსაც ამოწმებს შემდგომ ხელით შევამოწმე და სწორ პასუხებს, (მინიმალური სიგრძისა და კორეკტულ ბილიკის მქონე გზას) აბრუნებს.

ახალ ხაზებს შორის დაბეჭვდის ყველა კომბინაცია ვცადე მაგრამ არანაირი შედეგი არ გამოუღია
```
cout << end << path << endl;
cout << path << endl;
cout << endl << path;
```

ესაა ერთ-ერთი ტესტის მაგალითი, რომელზეც იჭრება და ქვემოთაა ჩემს მიერ ამ უკანასკნელი ტესტის მაგალითზე ხელით შეყვანილი ინპუთისას, რა გამოაქვს

> ```
> >>>>>> START TEST ON: Jack Nicholson <-> Meryl Streep
> >>>>>> Please wait, It takes several seconds ....
> !!!!>>>> Minimum path length Differs: Expected 1 But was: 0
> ~~~~~TEST CHECK FAILED~~~~~
> ```
> ```
> Actor or actress [or <enter> to quit]: Jack Nicholson
> Another actor or actress [or <enter> to quit]: Meryl Streep
>         Jack Nicholson was in "Heartburn" (1986) with Meryl Streep.
> ```

და ეს შემდეგი მაგალითიც, სადაც ბილიკის ზომას 3-ს ელოდება, მაგრამ რატომღაც ჩემს მიერ დაბეჭდილ გზის სიგრძეს 4-ად აღიქვამს. ხელითაც კი დავსერჩე და ამ ფილმებით ამ ბილიკის აწყობაც შესაძლებელია :დ

> ```
> >>>>>> START TEST ON: Brad Pitt <-> Duta Skhirtladze
> >>>>>> Please wait, It takes several seconds ....
> !!!!>>>> Minimum path length Differs: Expected 3 But was: 4
> ~~~~~TEST CHECK FAILED~~~~~
> ```
> ```
> Actor or actress [or <enter> to quit]: Brad Pitt 
> Another actor or actress [or <enter> to quit]: Duta Skhirtladze
>         Brad Pitt was in "Abby Singer" (2003) with Jeff Goldblum.
>         Jeff Goldblum was in "Fay Grim" (2006) with Mark Zak.
>         Mark Zak was in "Wolfsschlucht" (2003) with Duta Skhirtladze.
> ```

და საბოლოოდ ყველაზე საინტერესო, ჩემს მიერ დაწყებულ მსახიობს საერთოდ სხვაში ურევს.

> ```
> >>>>>> START TEST ON: Jerry Cain <-> Kevin Bacon
> >>>>>> Please wait, It takes several seconds ....
> !!!!>>>> Start Actors differs, Expected: Jerry Cain but was: Mary Tyler Moore
> ~~~~~TEST CHECK FAILED~~~~~
> ```
> ```
> Actor or actress [or <enter> to quit]: Jerry Cain
> Another actor or actress [or <enter> to quit]: Kevin Bacon
>         Jerry Cain was in "No Rules" (2005) with Dian Bachar.
>         Dian Bachar was in "Adventures of Rocky & Bullwinkle, The" (2000) with Robert De Niro.
>         Robert De Niro was in "Sleepers" (1996) with Kevin Bacon.
> ```

**დამატებითი ინფორმაცია:**

1. x64 WSL 2-ზე ვმუშაობ (წესით არ უნდა შეექმნა პრობლემა, ეს დასკვნა იქიდან გამომაქვს, რომ პირველი დავალება მშვენივრად მუშაობდა)**
2. x64 Ubuntu-ს VirtualBox-ზე რომ ვუშვებ ჩემს მიერ დაწერილ კოდს საერთოდ, იქრაშება Segmentation fault-ს აგდებს (წესით ესეც არ უნდა ხდებოდეს :დ და compatible უნდა იყოს )
3. WSL-ში როდესაც `actorFile`-ში განლაგებულ მსახიობის სახელსა და გვარს ვწვდები  ამ გზით: `(char*)actorFile + ((int*)actorFile)[N])`, სადაც N-მსახიობის ნომერია, ყველა მსახიობის ინფოს სწორედ იღებს, ხოლო როდესაც იდენტურ ხაზზს VirtualBox-ზე ვწერ ზოგჯერ მსახიობის სახელი და გვარი გამოაქვს, უმეტეს შემთხვევაში კი unknown character-ები და რენდომ სტრინგები.

**EDIT:**

1. WSL-ისა და VirtualBox-ის output-ის ამსახველი ფოტო: https://ibb.co/jW9bqzw

**Comment by iarigby** [comment]
@freeuni-paradigms/section-leaders help :D

**Comment by mdzam18** [comment]
გამარჯობა, მეც, რომ გავტესტე ჩემთან (char*)actorFile + ((int*)actorFile)[N])-ის დაბეჭდვა სწორად ბეჭდავდა სტრინგებს. ვფიქრობ, შესაძლოა, სადმე ბაიტების დათვლაში გეშლება და არასწორ მისამართს მიმართავ. მაინც გადაამოწმე კომპარატორ ფუნქცია, შესაძლოა მასშიც იყოს პრობლემა. კიდევ დავფიქრდები, თუ რაში შეიძლება იყოს საქმე, რომ უკეთ დაგეხმარო.

**Comment by d-chechelashvili** [comment]
დაბეჭდვის შეცდომა აღმოჩნდა, ოღონდ დაბეჭდვის ფორმატის არა, პასუხის გამოტანის კოდის სხვა ადგილას გადატანამ უშველა.

**Comment by LukeSamkharadze** [comment]
დავით შენ გაიხარე <3

* მაინც ტესტების ბრალი იყო საბოლოოდ :დ

**Comment by LukeSamkharadze** [comment]
> გამარჯობა, მეც, რომ გავტესტე ჩემთან (char*)actorFile + ((int*)actorFile)[N])-ის დაბეჭდვა სწორად ბეჭდავდა სტრინგებს. ვფიქრობ, შესაძლოა, სადმე ბაიტების დათვლაში გეშლება და არასწორ მისამართს მიმართავ. მაინც გადაამოწმე კომპარატორ ფუნქცია, შესაძლოა მასშიც იყოს პრობლემა. კიდევ დავფიქრდები, თუ რაში შეიძლება იყოს საქმე, რომ უკეთ დაგეხმარო.

@mdzam18 
მადლობა მარიამ გამოხმაურებისთვის.

ეს code snippet, რომელსაც VirtualBox-ზე ვიძახებ არანაირ მეხსიერების გათვლებს არსაჭიროებს, სწორედაც რომ ამ მიზეზის გამო ავღნიშნე მსგავსი პარადოქსული რესულტატი ჩემს პრობლემაში.

ეხლა ვცდილობდი VirtualBox-ზე გამეშვა ხელახლა ეს პროექტი, მაგრამ საბოლოოდ გავარკვიე რომ VirtualBox ვერაა კარგად. `apt-get install valgrind`-ზე აგდებს Segmentation fault-ს და კიდევ ბევრი პრობლემა აქვს :დ

მოკლედ მადლობა ყველას

**Comment by iarigby** [comment]
> მადლობა ყველას

VirtualBox-ის გარდა!
