### ISSUE TITLE
binary search

### ISSUE THREAD

**Issue by LevanSamadashvili** [freeuni-paradigms/assn-2-six-degrees#5]
**ორობით ძებნაზე** FAQ pdf-ში წერია რომ თქვენით არ დაწეროთ **bsearch** ფუნქცია გამოიყენეთო, სანამ მაგას ვნახავდი დაწერილი მქონდა და რამე პრობლემა ხო არ იქნება ჩვენით დაწერილ ორობით ძებნაზე, თუ სწორად მუშაობს რა თქმა უნდა.

**Comment by iarigby** [comment]
ტესტებზე თუ გადის არა. მაგრამ bsearch და მისნაირი ფუნქციების გამოყენება გამოცდებზე იქნება და სტანდარტულშიც ივარჯიშე

**Comment by LevanSamadashvili** [comment]
მადლობა
