### ISSUE TITLE
პირობაში წერია რომ მარტო IMDB-ს ფაილის დატესტვაც შეგვიძლია და როგორ უნდა დავტესტოთ?

### ISSUE THREAD

**Issue by mtuma19** [freeuni-paradigms/assn-2-six-degrees#8]

**Comment by d-chechelashvili** [comment]
ისეთი ტესტერები არაა პირდაპირ რომ დაგიწეროს კონკრეტულ ტესტზე გაიარა თუ ჩაიჭრა ან რამე. იგულისხმება, რომ ./imdb-test ის გაშვებისას ხელით შეყვანილ მონაცემებზე რას დააბრუნებს შეხედო შენით. შეგიძლია imdb-test-linux  sample აპლიკაციას შეადარო შენი პროგრამის აუთფუთი

**Comment by mtuma19** [comment]
აა გასაგებია, მადლობა
