### ISSUE TITLE
დავალების ატვირთვა

### ISSUE THREAD

**Issue by tsakh** [freeuni-paradigms/assn-2-six-degrees#9]
როგორც მივხვდი ქლასრუმზე მხოლოდ ორი ფაილის ზიპი: imdb.cc და six-degrees.cc უნდა ავტვირთოთ. დავალების ავტომატური ატვირთვის წესში როგორც წერია, დავალების დირექტორიაში უნა გავუშვათ ბრძანება ./zip.sh და ეგ ყველა ფაილს არ დაზიპავს? რამე პრობლემა არ შემქმნია ამის გამო, უბრალოდ მაინტერესებს.

**Comment by iarigby** [comment]
არ დაზიპავს, შეგიძლია გახსნა და წაიკითხო როგორ იძახებს zip ბრძანებას.

**Comment by tsakh** [comment]
წინაზე მხოლოდ ერთი ფაილის დაზიპვა იყო საჭირო და ეხლა მეთვითონ გამიჩნდა ეგ კითხვა, ტერმინალიდან რამდენიმე ფაილის ერთდროულად დაზიპვა როგორ ხდებათქო :დ მადლობა <3

**Comment by iarigby** [comment]
zip ბრძანებას უბრალოდ რამდენიმე ფაილს გადასცემ. zip.sh ში ვიძახებ zip
ბრძანებას სწორი ფაილებით, რომ თქვენ არ მოგიწიᲝთ აკრეფვა და შემთხვევით არ
შეგეშალოთ. ამიტომ გითხარი გახსნა და ნახვა, იქ წერია (ბოლო ხაზი რაცაა). და
შეგიძლია პირველი დავალების zip.shს შეადარო :)

**Comment by tsakh** [comment]
გასაგებია, არ ვიცოდი ეგეთი რაღაც თუ შესაძლებელი იყო :დ მადლობა დიდი
